# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CIN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CIN
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources'
  pod 'RxViewController'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'RIBs', '~> 0.9'
  pod ‘ObjectMapper’
  pod ‘SwiftyJSON’
  pod 'Then'
  target 'CINTests' do
    inherit! :search_paths
  # Pods for testing
  pod 'RxBlocking', '~> 4.0'
  pod 'RxTest', '~> 4.0'
  end

  target 'CINUITests' do
    # Pods for testing
  end

end
